name: tts_ci_ui
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - opencv
  - ffmpeg
  - gdown
  - pip
  - pip:
    - streamlit
    - torch
    - torchvision
    - tqdm
    - numba
    - openai
    - soxr
    - face_detection
    - audio
