name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        node-version: '20'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg

    - name: Download Wav2Lip checkpoint
      run: |
        pip install gdown
        gdown --id 1PyxYrrjLcKdhdyMMIXlhUYpnoWR9zN-T -O checkpoints/wav2lip_gan.pth

    - name: Run inference script
      run: python inference_for_ci.py --checkpoint_path checkpoints/wav2lip_gan.pth --face pic_files/pic.png
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
